name: metrics
channels:
  - conda-forge
dependencies:
  - python=3.10.13
  - mujoco=2.3.7
  - moviepy=1.0.3
  - dm-env=1.6
  - swig=4.1.1
  - pybullet=3.25
  - tensorboard=2.15.1
  - torchvision=0.15.2
  - matplotlib=3.8.2
  - torchmetrics=1.2.1
  - omegaconf=2.3.0
  - ml_dtypes=0.3.1
  - openai=1.5.0
  - gym=0.26.1
  - sqlite=3.44.2
  - wandb=0.16.1
  - labmaze=1.0.6
  - opt_einsum=3.3.0
  - dm-haiku=0.0.11
  - promise=2.3
  - scikit-learn=1.3.2
  - stable-baselines3=2.2.1
  - jupyter=1.0.0
  - opencv=4.8.0
  - gin-config=0.5.0
  - seaborn=0.13.0
  - cython=3.0.7
  - dill=0.3.7
  - box2d-py=2.3.8
  - lockfile=0.12.2
  - einops=0.7.0
  - glew=2.1.0
  - h5py=3.10.0
  - numpy=1.26.2
  - hydra-core=1.3.2
  - optax=0.2.2
  - scipy=1.12.0
  - pip:
    - jax==0.4.23
    - jaxlib==0.4.23
    - jaxopt==0.8.2
    - dm-haiku==0.0.12
    - simple-pytree==0.2.2
